local ESX = exports['es_extended']:getSharedObject()
RegisterCommand('record', function()
    StartRecording(1)
    ESX.ShowNotification("Started Recording!")
end, false)

RegisterCommand('clip', function()
    StartRecording(0)
end, false)

RegisterCommand('saveclip', function()
    StopRecordingAndSaveClip()
    ESX.ShowNotification("Saved Recording!")
end, false)

RegisterCommand('delclip', function()
    StopRecordingAndDiscardClip()
    ESX.ShowNotification("Deleted Recording!")
end, false)

RegisterCommand('editor', function()
    NetworkSessionLeaveSinglePlayer()
    ActivateRockstarEditor()
    ESX.ShowNotification("Later aligator!")
end, false)
